version: '4.44.3'

services:
  app:
    build: .
    container_name: node-backend
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mysql:
    image: mysql:8.0
    container_name: mysql_bd
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=user_bd
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '3311:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  
  adminer:
    image: adminer
    container_name: adminer_node_crud
    restart: always
    ports:
      - "8080:8080"
volumes:
  mysql_data: